spring.application.name=S3BucketDemoApplication
spring.cloud.aws.credentials.access-Key=MY_AWS_ACCESS_KEY
spring.cloud.aws.credentials.secret-Key=MY_AWS_SECRET_KEY
spring.cloud.aws.region.static=eu-north-1
spring.cloud.aws.s3.bucket=s3-demo-application-bucket